environment:
  matrix:
  - TARGET: i686-pc-windows-gnu
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
  - TARGET: x86_64-pc-windows-msvc
install:
  - SET PATH=%PATH%;C:\MinGW\bin;C:\MinGW\msys\1.0\bin

build: false

test_script:
  - sh -c "(env && pwd && cd -P . && ./configure)"
  - make check-lite
